/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BalcaoRouteImport } from './routes/balcao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ControleRouteImport } from './routes/controle'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as FiadoRouteImport } from './routes/fiado'
import { Route as GavetaRouteImport } from './routes/gaveta'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as SalaoRouteImport } from './routes/salao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BalcaoRoute = BalcaoRouteImport.update({
  id: '/balcao',
  path: '/balcao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ControleRoute = ControleRouteImport.update({
  id: '/controle',
  path: '/controle',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const FiadoRoute = FiadoRouteImport.update({
  id: '/fiado',
  path: '/fiado',
  getParentRoute: () => rootRouteImport,
} as any)
const GavetaRoute = GavetaRouteImport.update({
  id: '/gaveta',
  path: '/gaveta',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaoRoute = SalaoRouteImport.update({
  id: '/salao',
  path: '/salao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balcao': typeof BalcaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/controle': typeof ControleRoute
  '/delivery': typeof DeliveryRoute
  '/fiado': typeof FiadoRoute
  '/gaveta': typeof GavetaRoute
  '/historico': typeof HistoricoRoute
  '/salao': typeof SalaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balcao': typeof BalcaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/controle': typeof ControleRoute
  '/delivery': typeof DeliveryRoute
  '/fiado': typeof FiadoRoute
  '/gaveta': typeof GavetaRoute
  '/historico': typeof HistoricoRoute
  '/salao': typeof SalaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/balcao': typeof BalcaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/controle': typeof ControleRoute
  '/delivery': typeof DeliveryRoute
  '/fiado': typeof FiadoRoute
  '/gaveta': typeof GavetaRoute
  '/historico': typeof HistoricoRoute
  '/salao': typeof SalaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balcao'
    | '/configuracoes'
    | '/controle'
    | '/delivery'
    | '/fiado'
    | '/gaveta'
    | '/historico'
    | '/salao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balcao'
    | '/configuracoes'
    | '/controle'
    | '/delivery'
    | '/fiado'
    | '/gaveta'
    | '/historico'
    | '/salao'
  id:
    | '__root__'
    | '/'
    | '/balcao'
    | '/configuracoes'
    | '/controle'
    | '/delivery'
    | '/fiado'
    | '/gaveta'
    | '/historico'
    | '/salao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalcaoRoute: typeof BalcaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ControleRoute: typeof ControleRoute
  DeliveryRoute: typeof DeliveryRoute
  FiadoRoute: typeof FiadoRoute
  GavetaRoute: typeof GavetaRoute
  HistoricoRoute: typeof HistoricoRoute
  SalaoRoute: typeof SalaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balcao': {
      id: '/balcao'
      path: '/balcao'
      fullPath: '/balcao'
      preLoaderRoute: typeof BalcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controle': {
      id: '/controle'
      path: '/controle'
      fullPath: '/controle'
      preLoaderRoute: typeof ControleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiado': {
      id: '/fiado'
      path: '/fiado'
      fullPath: '/fiado'
      preLoaderRoute: typeof FiadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaveta': {
      id: '/gaveta'
      path: '/gaveta'
      fullPath: '/gaveta'
      preLoaderRoute: typeof GavetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salao': {
      id: '/salao'
      path: '/salao'
      fullPath: '/salao'
      preLoaderRoute: typeof SalaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalcaoRoute: BalcaoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ControleRoute: ControleRoute,
  DeliveryRoute: DeliveryRoute,
  FiadoRoute: FiadoRoute,
  GavetaRoute: GavetaRoute,
  HistoricoRoute: HistoricoRoute,
  SalaoRoute: SalaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
