import type { MenuCategory, MenuItem, RestaurantInfo } from "./types";

export const INITIAL_RESTAURANT_INFO: RestaurantInfo = {
  name: "Fluxo Gastronomia",
  description: "Cozinha artesanal, hambúrgueres gourmet, pratos clássicos e bebidas especiais.",
  logo: "🍽️",
  phone: "(11) 98888-1200",
  address: "Rua Gastronômica, 100 — Centro",
  isOpen: true,
  wifiNetwork: "Fluxo_Clientes",
  wifiPassword: "cardapioinstantaneo",
  businessHours: "Terça a Domingo · 11:30 às 23:00",
  averageTime: "25 - 35 min",
};

export const INITIAL_CATEGORIES: MenuCategory[] = [
  { id: "cat-1", name: "Lanches", sort_order: 1 },
  { id: "cat-2", name: "Pratos", sort_order: 2 },
  { id: "cat-3", name: "Entradas", sort_order: 3 },
  { id: "cat-4", name: "Bebidas", sort_order: 4 },
  { id: "cat-5", name: "Sobremesas", sort_order: 5 },
];

export const INITIAL_PRODUCTS: MenuItem[] = [
  {
    id: "prod-1",
    name: "X-Bacon",
    price: 38.0,
    category_name: "Lanches",
    emoji: "🍔",
    sold_out: false,
    description: "Hambúrguer artesanal 180g no pão brioche, bacon crocante em tiras, queijo cheddar derretido e maionese defumada da casa.",
    details: ["Blend bovino 180g", "Pão brioche tostado", "Queijo cheddar", "Bacon crocante"],
  },
  {
    id: "prod-2",
    name: "X-Burger Especial",
    price: 32.0,
    category_name: "Lanches",
    emoji: "🍔",
    sold_out: false,
    description: "Pão brioche selado na manteiga, hambúrguer suculento 180g, queijo prato derretido, alface americana fresca e tomate chapeado.",
    details: ["Blend bovino 180g", "Pão brioche", "Queijo prato", "Salada fresca"],
  },
  {
    id: "prod-3",
    name: "Combo Burger + Fritas",
    price: 58.0,
    category_name: "Lanches",
    emoji: "🍟",
    sold_out: false,
    description: "Nosso X-Burger Especial acompanhado de porção individual de batatas rústicas com alecrim e 1 refrigerante lata.",
    details: ["Acompanha batata rústica", "Refrigerante lata incluso"],
  },
  {
    id: "prod-4",
    name: "Picanha na Chapa 300g",
    price: 89.0,
    category_name: "Pratos",
    emoji: "🥩",
    sold_out: false,
    description: "Corte nobre de picanha maturada grelhada no ponto desejado, servida com arroz branco soltinho, farofa de ovos e vinagrete especial.",
    details: ["Picanha premium 300g", "Arroz branco", "Farofa de ovos", "Vinagrete"],
  },
  {
    id: "prod-5",
    name: "Risoto de Camarão",
    price: 68.0,
    category_name: "Pratos",
    emoji: "🍤",
    sold_out: false,
    description: "Arroz arbóreo italiano com camarões selecionados salteados no azeite, caldo aromático de frutos do mar e finalizado com parmesão grana padano.",
    details: ["Camarões rosa", "Arroz arbóreo", "Parmesão legítimo"],
  },
  {
    id: "prod-6",
    name: "Feijoada Completa",
    price: 52.0,
    category_name: "Pratos",
    emoji: "🍲",
    sold_out: false,
    description: "Tradicional feijoada com carnes nobres desengorduradas, acompanhada de arroz, couve refogada no alho, bisteca grelhada, torresmo crocante e laranja.",
    details: ["Carnes nobres", "Couve refogada", "Torresmo crocante"],
  },
  {
    id: "prod-7",
    name: "Pizza Margherita",
    price: 52.0,
    category_name: "Pratos",
    emoji: "🍕",
    sold_out: false,
    description: "Massa de fermentação natural de 48h, molho de tomate pelado San Marzano, muçarela de búfala, manjericão fresco e azeite extravirgem.",
    details: ["Fermentação 48h", "Molho artesanal", "Manjericão fresco"],
  },
  {
    id: "prod-8",
    name: "Batata Frita Rústica",
    price: 26.0,
    category_name: "Entradas",
    emoji: "🍟",
    sold_out: false,
    description: "Batatas especiais cortadas com casca, temperadas com sal marinho, alecrim fresco e alho confitado. Acompanha maionese de ervas.",
    details: ["Porção 350g", "Alecrim fresco", "Maionese da casa"],
  },
  {
    id: "prod-9",
    name: "Bolinho de Bacalhau (6 un)",
    price: 38.0,
    category_name: "Entradas",
    emoji: "🐟",
    sold_out: true,
    description: "Receita portuguesa tradicional feita com legítimo bacalhau Gadus Morhua, batata e salsinha fresca. Crocante por fora e cremoso por dentro.",
    details: ["6 unidades", "Legítimo bacalhau", "Azeite extravirgem"],
  },
  {
    id: "prod-10",
    name: "Pão de Alho Especial",
    price: 22.0,
    category_name: "Entradas",
    emoji: "🥖",
    sold_out: false,
    description: "Baguete crocante recheada com pasta cremosa de alho poró, muçarela e ervas finas, gratinada ao forno a lenha.",
    details: ["2 baguetes médias", "Gratinado com muçarela"],
  },
  {
    id: "prod-11",
    name: "Coca-Cola Lata 350ml",
    price: 8.0,
    category_name: "Bebidas",
    emoji: "🥤",
    sold_out: false,
    description: "Refrigerante gelado servido com copo com gelo e limão.",
  },
  {
    id: "prod-12",
    name: "Suco de Laranja 400ml",
    price: 12.0,
    category_name: "Bebidas",
    emoji: "🍊",
    sold_out: false,
    description: "Suco natural 100% fruta espremida na hora, sem adição de açúcar ou conservantes.",
  },
  {
    id: "prod-13",
    name: "Chopp Artesanal 500ml",
    price: 18.0,
    category_name: "Bebidas",
    emoji: "🍺",
    sold_out: false,
    description: "Pilsen puro malte super gelado com colarinho cremoso e notas aromáticas suaves.",
  },
  {
    id: "prod-14",
    name: "Água Mineral com Gás 500ml",
    price: 6.0,
    category_name: "Bebidas",
    emoji: "💧",
    sold_out: false,
    description: "Água mineral gaseificada naturalmente em garrafa pet 500ml.",
  },
  {
    id: "prod-15",
    name: "Vinho Tinto (Taça)",
    price: 24.0,
    category_name: "Bebidas",
    emoji: "🍷",
    sold_out: false,
    description: "Taça de vinho tinto Cabernet Sauvignon encorpado com notas de frutas vermelhas.",
  },
  {
    id: "prod-16",
    name: "Pudim de Leite Condensado",
    price: 15.0,
    category_name: "Sobremesas",
    emoji: "🍮",
    sold_out: false,
    description: "Fatia generosa do clássico pudim brasileiro, sem furinhos, extremamente lisinho e com calda de caramelo brilhante.",
  },
  {
    id: "prod-17",
    name: "Petit Gâteau com Sorvete",
    price: 28.0,
    category_name: "Sobremesas",
    emoji: "🍫",
    sold_out: false,
    description: "Bolo de chocolate belga morno com recheio cremoso e escorrendo, servido com bola de sorvete de baunilha artesanal.",
  },
  {
    id: "prod-18",
    name: "Cheesecake de Frutas Vermelhas",
    price: 26.0,
    category_name: "Sobremesas",
    emoji: "🍰",
    sold_out: false,
    description: "Base crocante de biscoito amanteigado, recheio aveludado de cream cheese e cobertura farta de calda artesanal de amoras, morangos e framboesas.",
  },
];
